/*
    layout.js 

    Overall layout of my app
*/

import './globals.css';
import SocialDirectry from './Components/SocialDirectory.js'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SocialDirectry />
        {children}
      </body>
    </html>
  )
}
